### ISSUE TITLE
bindGLFW_WGL Error: cannot return non-void from `void` function

### ISSUE THREAD

**Issue by tofuninja** [BindBC/bindbc-glfw#14]
Error: cannot return non-void from `void` function

 void loadGLFW_NSGL() {
          import bindbc.loader.sharedlib : errorCount;
          if(!isGLFWLoaded) return false;
          bindGLFWSymbol(cast(void**)&glfwGetWGLContext,"glfwGetWGLContext");
      }

**Comment by tofuninja** [comment]
The bindGLFW_WGL mixin causes compile errors, the fix is trivial..

**Comment by mdparker** [comment]
> The bindGLFW_WGL mixin causes compile errors, the fix is trivial..

What are the errors?

**Comment by tofuninja** [comment]
Line 561.. 
There error is "Error: cannot return non-void from void function"

**Comment by mdparker** [comment]
I see. That 'loadGLFW_NSGL' threw me off. I thought you were reporting two errors. I see now that was an error in the source--it was supposed to be `loadGLFW_WGL' function. I've fixed that and a couple of other problems.

It all compiles and loads for me. It's available in v1.0.1 once the dub repository refreshes.

Thanks for reporting!

**Comment by tofuninja** [comment]
Thanks for the quick response :)
