### ISSUE TITLE
Error: undefined identifier:  isGLFWLoaded

### ISSUE THREAD

**Issue by WhatMeWorry** [BindBC/bindbc-glfw#4]
I get this one error about isGLFWLoaded.  The other functions are fine.

.\common\derelict_libraries.d(101,14): Error: undefined identifier isGLFWLoaded
AIL .dub\build\application-debug-windows-x86_64-ldc_2083-B17D37CE3FF9DAC34CB3E8A692CBE9CF\ 06_03_04_levels executable
dc2 failed with exit code 1.
\..\duball exited with code 2

Believe I can get by without it.  

    GLFWSupport ret = loadGLFW();

    if (ret == GLFWSupport.noLibrary) 
        writeln("No FreeImage shared library was detected");
    if (ret == GLFWSupport.badLibrary) 
        writeln("One or more symbols failed to load.");

    if (isGLFWLoaded())
    {
        GLFWSupport glfwVer = loadedGLFWVersion();
        if (glfwVer == GLFWSupport.glfw30)
            writeln("GLFW - Graphics Library FrameWork - Version 3.0 successfully loaded");
        else if (glfwVer == GLFWSupport.glfw31)
            writeln("GLFW - Graphics Library FrameWork - Version 3.1 successfully loaded");
        else if (glfwVer == GLFWSupport.glfw32)
            writeln("GLFW - Graphics Library FrameWork - Version 3.2 successfully loaded");
        else
            writeln("An unexpected version of GLFW - Graphics Library FrameWork - was loaded");
    }
    else
        writeln("No version of the GLFW library was loaded");

**Comment by mdparker** [comment]
Is it working now?
